### ISSUE TITLE
License, Merge-Requests

### ISSUE THREAD

**Issue by struckma** [trawiasty/checkstyle-to-json#1]
Dear @paweltatarczuk ,

For our CI/CD I would like to use you small checkstyle converter script and extend it a bit. However, I did not find any license information in the repository. If you could decide for a licenseI would I simply fork it and send you a PR after my modifications (so far, robustness, if lints w/o column are reported).

Thank you and best wishes

Stephan

**Comment by paweltatarczuk** [comment]
Hi @struckma,

I have added the MIT license, feel free to fork the repo and adjust it to your needs. 

Have a nice day :)

**Comment by struckma** [comment]
Thank you very much. I'll come back to you with a PR likely later.
